### ISSUE TITLE
Can't open the file

### ISSUE THREAD

**Issue by AbdulrahmanHadz** [rdavisau/sg-unpack#1]
when i press on the .exe file, a cmd looking window pops up then goes away, any help?

**Comment by rdavisau** [comment]
Hi -

Yes, you should run this from the command line with arguments corresponding to what you want to do. So first, open the command line, then call the .exe from there (replace path_to_exe with your path):

c:\path_to_exe\sg-unpack.exe -i C:\Program Files (x86)\Steam\steamapps\common\STEINS;GATE\USRDIR -f .ogg -o C:\SG -q true

^ above is adapted from the sample on the readme page and would dump all the music (.ogg files) into c:\SG
