### ISSUE TITLE
Confusing to set up ????

### ISSUE THREAD

**Issue by FoxerMoxer** [rdavisau/sg-unpack#6]
I wanted to get the audio files from the game because I couldn't seem to find them anywhere else. so I tried to set this up and for me at least when you say things like command line and such it makes it more difficult I assume you're referring to CMD or PowerShell? anyways It's also difficult to understand what just a template is and what actually needs to be in the command for example this "i, --input-path" do I write --input-path? The way I've been doing it was by going to power shell doing "cd [Then the directory for sg-unpack]" then I try this "[ECT]STEINS;GATE\USRDIR\voice.mpk" BTW the ECT In the file location just stands for the steam stuff. Anyways I've spent the last hour or so trying to get this to work. so if possible please word it better please it would be a huge help

**Comment by rdavisau** [comment]
Hello. You should be able to use either cmd or powershell. Below for cmd (parts inside square brackets need to be replaced):

first:
`cd [sg-unpack-directory]`

then for voice files:
`sg-unpack.exe -i [path-to-sg]\USRDIR\voice.mpk -o [path-you-want-files-to-go]`

for bgm files:
`sg-unpack.exe -i [path-to-sg]\USRDIR\bgm.mpk -o [path-you-want-files-to-go]`

for example, using typical path of steam edition of sg, outputting bgm files to c:\SG:
`sg-unpack.exe -i C:\Program Files (x86)\Steam\steamapps\common\STEINS;GATE\USRDIR\bgm.mpk -o c:\SG`

**Comment by FoxerMoxer** [comment]
For some reason it still doesn't work it says "sg-unpack.exe : The term 'sg-unpack.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included:" I did cd [File location of Sg-Unpack ] then I did "sg-unpack.exe -i [SteamETC]\STEINS;GATE\USRDIR\voice.mpk -o D:\" Also by the way these instructions are much better. Thank you :)

**Comment by rdavisau** [comment]
Sounds like you might be in Powershell, where you need to explicitly specify the path to a file you want to execute. In that case all the invocations of sg-unpack.exe need to be prefixed with "./" (means 'current directory'): 

voice files:
`./sg-unpack.exe -i [path-to-sg]\USRDIR\voice.mpk -o [path-you-want-files-to-go]`

for bgm files:
`./sg-unpack.exe -i [path-to-sg]\USRDIR\bgm.mpk -o [path-you-want-files-to-go]`
